# Generated by Django 4.0.5 on 2022-07-08 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=10, null=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='mascotas')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categoria')),
            ],
        ),
    ]
